name: payment_card
description: A custom widget for creating beautiful payment(eg. credit or debit) cards on flutter.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/images/
    - assets/images/bg/
    - assets/icons/
    - assets/icons/jpg/
    - assets/icons/png/
    - assets/icons/svg/

  fonts:

    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata/Inconsolata-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inconsolata/Inconsolata-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inconsolata/Inconsolata-Light.ttf
          weight: 300
        - asset: assets/fonts/Inconsolata/Inconsolata-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inconsolata/Inconsolata-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inconsolata/Inconsolata-Black.ttf
          weight: 900
        - asset: assets/fonts/Inconsolata/Inconsolata-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inconsolata/Inconsolata-ExtraBold.ttf
          weight: 800
